// A browse prefix is "" (bucket root) or a "/"-terminated S3 key prefix
// ("docs/", "docs/sub/"). Segments never contain "/".

export const prefixToSegments = (prefix: string): string[] =>
  prefix === "" ? [] : prefix.slice(0, -1).split("/")

export const segmentsToPrefix = (segments: string[]): string =>
  segments.length === 0 ? "" : `${segments.join("/")}/`

export const entryName = (key: string): string => key.slice(key.lastIndexOf("/") + 1)

// The directory part of an object key, "" at the bucket root. The other half
// of entryName: `keyParent(k) + entryName(k) === k`.
export const keyParent = (key: string): string => {
  const slash = key.lastIndexOf("/")

  return slash === -1 ? "" : key.slice(0, slash + 1)
}

export const dirName = (dirPrefix: string): string => entryName(dirPrefix.slice(0, -1))

// Splits a file name into the part a suffix goes after and its extension. A
// leading dot is part of the stem (".bashrc" has no extension), so a dotfile
// does not turn into an extension-only name when something is appended.
export const splitExtension = (name: string): { stem: string; ext: string } => {
  const dot = name.lastIndexOf(".")

  return dot <= 0 ? { stem: name, ext: "" } : { stem: name.slice(0, dot), ext: name.slice(dot) }
}

// "." / ".." segments survive percent-encoding as dot segments and would be
// rewritten by browser/proxy path normalization; a segment ending in a dot
// ("abc.") can trip the same normalization on some proxies. Force any
// trailing dot(s) into %2E so the segment survives verbatim.
const encodeSegment = (segment: string): string => {
  if (segment === ".") return "%2E"
  if (segment === "..") return "%2E%2E"
  const encoded = encodeURIComponent(segment)

  return encoded.replace(/\.+$/, (match) => "%2E".repeat(match.length))
}

export const prefixToUrlPath = (prefix: string): string =>
  prefixToSegments(prefix).map(encodeSegment).join("/")

export const keyToUrlPath = (key: string): string =>
  key.split("/").map(encodeSegment).join("/")

// React Router splat params arrive percent-decoded. Segments are kept as-is,
// including empty ones from a "//" in the key, so a prefix generated by
// prefixToUrlPath always reads back to the same prefix; "" is bucket root
// rather than one empty segment, matching prefixToSegments("").
// A single trailing "/" (produced by dirHref appending "/" to prefixToUrlPath
// output) is stripped here so `/browse/foo/` and `/browse/foo` both resolve
// to segments ["foo"]. Internal "//" is preserved.
export const splatToPrefix = (splat: string): string => {
  const clean = splat.endsWith("/") ? splat.slice(0, -1) : splat

  return segmentsToPrefix(clean === "" ? [] : clean.split("/"))
}

// encodeURIComponent leaves the RFC 3986 sub-delims !*'() unescaped. S3
// CopySource keys and RFC 5987 filename* both need those percent-encoded too
// (a stray ' would collide with the UTF-8'' delimiter, ( ) can trigger
// aggressive proxy filters, and * / ! are reserved in several contexts).
const escapeSubDelims = (encoded: string): string =>
  encoded.replace(/['()*!]/g, (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`)

// Encodes a key for use inside a URL path (CopySource, presign path), keeping
// "/" as the segment separator.
export const encodeStrictKey = (key: string): string =>
  key.split("/").map((seg) => escapeSubDelims(encodeURIComponent(seg))).join("/")

// Encodes a filename for use as an RFC 5987 filename* value (no "/" preserved,
// the whole string is a single token).
export const encodeFilenameStrict = (filename: string): string =>
  escapeSubDelims(encodeURIComponent(filename))
