// A browse prefix is "" (bucket root) or a "/"-terminated S3 key prefix
// ("docs/", "docs/sub/"). Segments never contain "/".

export const prefixToSegments = (prefix: string): string[] =>
  prefix === "" ? [] : prefix.slice(0, -1).split("/")

export const segmentsToPrefix = (segments: string[]): string =>
  segments.length === 0 ? "" : `${segments.join("/")}/`

export const parentPrefix = (prefix: string): string =>
  segmentsToPrefix(prefixToSegments(prefix).slice(0, -1))

export const entryName = (key: string): string => key.slice(key.lastIndexOf("/") + 1)

export const dirName = (dirPrefix: string): string => entryName(dirPrefix.slice(0, -1))

// "." / ".." segments survive percent-encoding as dot segments and would be
// rewritten by browser/proxy path normalization; a segment ending in a dot
// ("abc.") can trip the same normalization on some proxies. Force any
// trailing dot(s) into %2E so the segment survives verbatim.
const encodeSegment = (segment: string): string => {
  if (segment === ".") return "%2E"
  if (segment === "..") return "%2E%2E"
  const encoded = encodeURIComponent(segment)

  return encoded.replace(/\.+$/, (match) => "%2E".repeat(match.length))
}

export const prefixToUrlPath = (prefix: string): string =>
  prefixToSegments(prefix).map(encodeSegment).join("/")

export const keyToUrlPath = (key: string): string =>
  key.split("/").map(encodeSegment).join("/")

// React Router splat params arrive percent-decoded. Segments are kept as-is,
// including empty ones from a "//" in the key, so a prefix generated by
// prefixToUrlPath always reads back to the same prefix; "" is bucket root
// rather than one empty segment, matching prefixToSegments("").
// A single trailing "/" (produced by dirHref appending "/" to prefixToUrlPath
// output) is stripped here so `/_browse/foo/` and `/_browse/foo` both resolve
// to segments ["foo"]. Internal "//" is preserved.
export const splatToPrefix = (splat: string): string => {
  const clean = splat.endsWith("/") ? splat.slice(0, -1) : splat

  return segmentsToPrefix(clean === "" ? [] : clean.split("/"))
}

// encodeURIComponent leaves the RFC 3986 sub-delims !*'() unescaped. S3
// CopySource keys and RFC 5987 filename* both need those percent-encoded too
// (a stray ' would collide with the UTF-8'' delimiter, ( ) can trigger
// aggressive proxy filters, and * / ! are reserved in several contexts).
const escapeSubDelims = (encoded: string): string =>
  encoded.replace(/['()*!]/g, (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`)

// Encodes a key for use inside a URL path (CopySource, presign path), keeping
// "/" as the segment separator.
export const encodeStrictKey = (key: string): string =>
  key.split("/").map((seg) => escapeSubDelims(encodeURIComponent(seg))).join("/")

// Encodes a filename for use as an RFC 5987 filename* value (no "/" preserved,
// the whole string is a single token).
export const encodeFilenameStrict = (filename: string): string =>
  escapeSubDelims(encodeURIComponent(filename))
